# Generated by Django 4.1.9 on 2023-06-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0003_fileversion_url_fileversion_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="file_hash",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
